### ISSUE TITLE
大神，你在博客里写的”分布式网络爬虫的基本实现简述“内容不全呀

### ISSUE THREAD

**Issue by 458138584** [mrchor/spiderForPM25#1]
zookeeper及代理都没写，能补全么？不知道怎么私信。。

**Comment by mrchor** [comment]
首先，这个项目是以前读研的时候做的，现在已经毕业了，由于笔记本磁盘损坏，代码找不到了，而且也没时间写了。以下给你一个大概的思路，你可以看看~
1、zookeeper：大概的思想是这样的，要求每个爬虫在zk上注册服务（目录），再写一个java作业，启动并实时监控zk上爬虫的注册目录是否存在，如果不存在，去对应的服务器重启爬虫，如果失败三次，则可以发报警信息（具体实现就看是短信还是邮件了）
2、代理这一块的话，就比较简单了，网上卖代理IP的多得很，你可以随便找几家网站看看去，代理IP的设置，这个很简单了吧，网上搜一下吧。
